wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 128
BUFFER_SIZE:
  desc: null
  value: 1000000
EPSILON:
  desc: null
  value: 0.8
GAMMA:
  desc: null
  value: 0.99
LEARNING_RATE:
  desc: null
  value: 0.001
TAU:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 3
      2:
      - 3
      4: 3.9.5
      5: 0.11.0
      8:
      - 3
      - 5
